In [1]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [2]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
